# Generated by Django 2.2.5 on 2019-09-15 19:50

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exchange_core', '0005_auto_20190914_0521'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('left_value', models.DecimalField(decimal_places=8, default=Decimal('0.00'), max_digits=20)),
                ('right_value', models.DecimalField(decimal_places=8, default=Decimal('0.00'), max_digits=20)),
                ('lower_side', models.CharField(choices=[('O', 'O'), ('L', 'L'), ('R', 'R')], default='L', max_length=1)),
                ('statement', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='binary_report', to='exchange_core.Statement')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BinaryTree',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('position', models.CharField(choices=[('O', 'O'), ('L', 'L'), ('R', 'R')], default='O', max_length=1)),
                ('value', models.DecimalField(decimal_places=8, default=Decimal('0.00'), max_digits=20)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='children', to='binary.BinaryTree')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('parent', 'position')},
            },
        ),
    ]
